### ISSUE TITLE
Exclude Paths Issue

### ISSUE THREAD

**Issue by jimcmahon** [rycus86/prometheus_flask_exporter#108]
Not sure if this is necessarily an issue or I'm just not sure how to do it. My project uses Swagger docs and our API of course receives requests for those webpages. We are not interested in tracking those endpoints. Right now I create a histogram and a counter to run on all of our endpoints using the register_default method. I assume I can use the excluded_paths to not track any metrics for endpoints matching the regex expressions passed in as a list for this argument. 

I use the following argument when creating the PrometheusMetrics object: excluded_paths=["^/swagger/.*$"]

However I am still seeing the following when I hit the metrics endpoint:
![image](https://user-images.githubusercontent.com/79717131/135570248-0ac42ae9-ecd5-432a-bf4d-2384ad1a8a30.png)

Is there something I am obviously doing wrong here?

**Comment by rycus86** [comment]
Can you share more of your config please? Is `by_path_counter` a custom metric you set up? If so, how's that done? Thanks!

**Comment by jimcmahon** [comment]
`
metrics = PrometheusMetrics(
        app=flask_app, defaults_prefix="/api/v1", export_defaults=False, excluded_paths=["^/swagger/.*$"]
    )

metrics.register_default(
        metrics.counter(
            name="by_path_counter",
            description="Request count by request paths",
            labels={"path": lambda: render_path(request, routes)},
        )
    )

    metrics.register_default(
        metrics.histogram(
            name="requests_by_status_and_path",
            description="Response time by status code, path, and method",
            labels={
                "status": lambda r: r.status_code,
                "path": lambda: render_path(request, routes),
                "method": lambda: request.method
            },
            buckets=(
                0.005,
                0.01,
                0.025,
                0.05,
                0.075,
                0.1,
                0.25,
                0.5,
                0.75,
                1.0,
                2.5,
                5.0,
            ),
        )
    )`

render_path is a helper method to get particular paths when we are using IDs. For the purposes of the example shown above it is returning the exact paths shown in the screenshot above.

**Comment by rycus86** [comment]
Hm, I suspect that maybe the exclusion only applies to default paths, let check it later. Thanks!

**Comment by rycus86** [comment]
I believe https://github.com/rycus86/prometheus_flask_exporter/commit/73efe45b755d6113cbaf03373662b4ed0b4371cd should fix this for you, let me know if you run into trouble with it. (you'll need to use version `0.18.3` once it's available from https://github.com/rycus86/prometheus_flask_exporter/actions/runs/1294404509)

**Comment by jimcmahon** [comment]
I see that there is now a new value, exclude_user_defaults. Is that an argument that is used when instantiating the PrometheusMetrics object?

**Comment by rycus86** [comment]
It is, but it's enabled by default, so your code should work without any changes to what you posted above (just be on the latest version)

**Comment by jimcmahon** [comment]
I am still seeing the issue unfortunately: 
![image](https://user-images.githubusercontent.com/79717131/135693400-64e8a696-7054-447a-9f62-c8dce4086c8f.png)

My pipfile.lock showing the version of the module:
![image](https://user-images.githubusercontent.com/79717131/135693436-8d49a8d4-44f2-4e1f-9a4e-2aae7587d582.png)

**Comment by rycus86** [comment]
Hmmm, that's interesting. Try specifying the parameter in the constructor then like it's done in the unit test in the commit above, but shouldn't be necessary.

Another thing to mention is that register_default should be called after the routes have been registered (as mentioned in the README). Is that how it's done for you?

**Comment by jimcmahon** [comment]
Yes, I do add the routes. I needed to do pienv uninstall and then reinstall since I was finding no references to this new variable. After doing that the swagger endpoints are no longer appearing :).

**Comment by rycus86** [comment]
Great, I'm glad it worked after the update! :) 
I'll close this issue now, but feel free to reopen (or open a new one) if you're still having issues with it.
